### ISSUE TITLE
TypeError when trying to format with black

### ISSUE THREAD

**Issue by nobodyinperson** [drillan/jupyter-black#13]
Hi,

Thanks for this extension. However, I can't use it because it always throws this error in my face:

![Bildschirmfoto_2019-12-04_09-59-14](https://user-images.githubusercontent.com/19148271/70128197-bf550f80-167c-11ea-92a2-c03823a7b4cd.png)

This happens in an existing notebook, in a fresh notebook, from the button and via the CTRL-B keyboard shortcut.

Running the notebook with `--log-level=DEBUG` only shows these 4 lines when the error occurs:

```log
[D 10:12:42.912 NotebookApp] activity on ffbe4112-f925-46b3-91a4-5e09801c2865: status
[D 10:12:42.914 NotebookApp] activity on ffbe4112-f925-46b3-91a4-5e09801c2865: execute_input
[D 10:12:42.928 NotebookApp] activity on ffbe4112-f925-46b3-91a4-5e09801c2865: error
[D 10:12:42.931 NotebookApp] activity on ffbe4112-f925-46b3-91a4-5e09801c2865: status
```

My environment:

```bash
> lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
> firefox -v
Mozilla Firefox 70.0.1
> vivaldi --version
Vivaldi 1.15.1147.64
> python3 -V
Python 3.6.9
> pip3 show black
Name: black
Version: 18.9b0
Summary: The uncompromising code formatter.
Home-page: https://github.com/ambv/black
Author: Łukasz Langa
Author-email: lukasz@langa.pl
License: MIT
Location: /home/yann/.local/lib/python3.6/site-packages
Requires: click, appdirs, attrs, toml
Required-by: clean-ipynb
> pip3 show jupyter_contrib_nbextensions
Name: jupyter-contrib-nbextensions
Version: 0.5.1
Summary: A collection of Jupyter nbextensions.
Home-page: https://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
Author: ipython-contrib and jupyter-contrib developers
Author-email: jupytercontrib@gmail.com
License: BSD
Location: /home/yann/.local/lib/python3.6/site-packages
Requires: traitlets, nbconvert, notebook, ipython-genutils, jupyter-nbextensions-configurator, jupyter-contrib-core, jupyter-core, pyyaml, tornado, jupyter-highlight-selected-word, lxml, jupyter-latex-envs
Required-by: 
```

I previously installed the extension manually as instructed in the README. Same error.

I might just be blind.

Any ideas?

**Comment by madebyollin** [comment]
I ran into this as well. The underlying cause of the issue was having an out-of-date `black` install (specifically, I was on `black-18.9b0`, which [had a different signature](https://github.com/psf/black/commit/36d3c516d3c09fc5f05c420900dd6b854e3c8bbd#diff-a75051ebf8e3452bf3d590c186944252L624) for `black.format_str`). 

To fix, run:
```bash
python3 -m pip install --upgrade black
```
And restart the notebook server.

**Comment by nobodyinperson** [comment]
Wow, how did I now upgrade `black` before posting this...

Thanks @madebyollin!
