### ISSUE TITLE
Please add a License

### ISSUE THREAD

**Issue by mafeko** [drillan/jupyter-black#15]
Hi @drillan 
thanks a lot for putting effort in this extension.

I really do like it and use it a lot in personal projects now.
However I can't legally use it at work since there is no license attached.

(Of course for my use-case I would prefer a rather "open" one, but that should be left to your decision [see choose a license](https://choosealicense.com))

Therefore I'm kindly asking you to pick a license and add it to the repository.
Thanks
Martin.

**Comment by drillan** [comment]
I have added a [license](https://github.com/drillan/jupyter-black/blob/master/LICENSE).
