### ISSUE TITLE
Cannot apply on multiple cells

### ISSUE THREAD

**Issue by KwatME** [drillan/jupyter-black#2]
Like `jupyter-black` :)

I found one small glitch: when selecting multiple cells and then applying `black`, it applies to only the last cell. I hope we could make it apply on all selected cells instead.

Thanks,
Kwat

**Comment by MarvinT** [comment]
Here's an alternative solution that solves this issue:
https://gist.github.com/MarvinT/a072aa992e977496974aaf492287b08c
and 
https://marvint.github.io/Black-Jupyter/
