### ISSUE TITLE
[Question]: How to use via commandline

### ISSUE THREAD

**Issue by paniash** [drillan/jupyter-black#22]
Hi!

I was wondering if it's possible to run this extension via the commandline, say something along the lines of 

```python
python3 -m jupyter-black demo.ipynb
```

which formats all the cells in `demo.ipynb`. Thanks in advance!

**Comment by mu22le** [comment]
I came here with the same question, but this project does not provide any python code, just the infrastructure to run a package (black) inside jupyter. 

Unless there is a way to run jupyter extensions from the command line I am afraid the answer to this is no.

**Comment by paniash** [comment]
@mu22le Hi! I came across a utility that works with the commandline. See [this](https://github.com/tomcatling/black-nb).

Cheers!
