### ISSUE TITLE
Black type error

### ISSUE THREAD

**Issue by jason-neal** [drillan/jupyter-black#4]
First time using jupyter-black after installation I get a popup with.
```
black extension
 Error: TypeError
format_str() takes 1 positional argument but 2 were given
````

Python 3.6.6
black-19.3b0

**Comment by timsainb** [comment]
I get the same error with the same python / black versions.

**Comment by timsainb** [comment]
I tried downgrading to the previous version of black (18.9b0) and no longer get the error

**Comment by jason-neal** [comment]
I confirm that I also get it to work on 18.9b0.

**Comment by MarvinT** [comment]
I've got it to work on my fork and PR #7 if anyone wants to have the most recent black installed for whatever reason...

**Comment by drillan** [comment]
@MarvinT Thank you for your pull request.It worked fine in my environment.

**Comment by MarvinT** [comment]
https://gist.github.com/MarvinT/a072aa992e977496974aaf492287b08c
and 
https://marvint.github.io/Black-Jupyter/

I ended up writing these to create a solution that would use allow for the use of both the new and the old versions of Black. It also demonstrates using this in code-prettify for an alternative implementation.
