### ISSUE TITLE
Skip jupyter magic lines

### ISSUE THREAD

**Issue by jason-neal** [drillan/jupyter-black#5]
I have a cell that has jupyter magic in it.
```
%%time
# Stuff to time
a = 1
```
Currently black fails it is not valid python.

```
black extension
 Error: InvalidInput
Cannot parse: 1:0: %%time
```

I can get around this by temporarily commenting out the line when running black but would it be possible to just skip these magic lines?

**Comment by MarvinT** [comment]
Here's an alternative solution that solves this issue:
https://gist.github.com/MarvinT/a072aa992e977496974aaf492287b08c
and 
https://marvint.github.io/Black-Jupyter/
